 
import "@/styles/highlight-js/github-dark-dimmed.css";

import { extractHeadings } from 'extract-md-headings'
import { promises as fs } from "fs";
import { usePathname } from 'next/navigation' 

import Sidebar from "@/components/sidebar";
/* export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} */


/* 
export const getStaticProps = async () => {
  const headings = extractHeadings("/blog/whats-a-curl")

  console.log("headings", headings)

  return {
    props: {
      headings,
    },
  }
} */


export default async function MdxLayout({
  children
}: {
  children: React.ReactNode
}) {


  const raw = await fs.readFile("/blog/javascript-in-a-nutshell", "utf-8");
  //server
/*   const headings = extractHeadings("/blog/whats-a-curl")

  console.log("headings", headings)
   */
  
  const pathname = usePathname()
  const slug = pathname.split('/').pop()

  console.log("pathname", slug)


    return(


    <>

      <div className='max-w-full flex flex-row  justify-start items-start'>
      <aside className='flex sticky top-11 '>
        <nav className=" ">
          <h2 className="uppercase">Table of Contents</h2>
          <ul className='list-none'>
            <li><a href='#'>First</a></li>
            <li><a href='#'>Second</a></li>
            <li><a href='#'>Third</a></li>
            <li><a href='#'>Fourth</a></li>
          </ul>
        </nav>

      </aside>

        <article className='flex-grow flex-shrink basis-96 p-10 text-pretty' style={{ maxWidth: 'min(42.875rem, 100%)' }}>
          {children}
        </article>
        <Sidebar/>


      </div>

    </>
  )
}
