import "@/styles/highlight-js/github-dark-dimmed.css";



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MdxLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>

      <div className='flex flex-col '>

        <div className='bg-red-600 mr-60 p-5' >
          {children}
        </div>
      </div>

    </>
  )
}
