'use client'
import "@/styles/highlight-js/github-dark-dimmed.css";
import { useParams } from "next/navigation";

import { usePathname } from 'next/navigation'
/* export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} */

export default function MdxLayout({
  children, params
}: {
  children: React.ReactNode
  params: ReturnType<typeof useParams>
}) {



  const pathname = usePathname()

  console.log(pathname)

  



  return (
    <>

      <div className='max-w-full flex flex-row  justify-start items-start'>

        <article className='flex-grow flex-shrink basis-96 p-10 text-pretty' style={{ maxWidth: 'min(42.875rem, 100%)' }}>
          {children}
        </article>
        <aside className='flex sticky top-11 '>
          <nav className=" ">
            <h2 className="uppercase">Table of Contents</h2>
            <ul className='list-none'>
              <li><a href='#'>First</a></li>
              <li><a href='#'>Second</a></li>
              <li><a href='#'>Third</a></li>
              <li><a href='#'>Fourth</a></li>
            </ul>
          </nav>

        </aside>

      </div>

    </>
  )
}
