
export const projects: ProjectItem[] = [
    {
      isPublished: true,
      isFeatured: true,
      updatedOn: "2024-06-01",
      publishedOn: "2024-06-01",
      slug: "linkedin-post-scheduler",
      title: "LinkedIn Post Scheduler",
      subtitle: "A LinkedIn post scheduler that I would like to use myself",
      tags: ["New", "TypeScript", "React", "Supabase", "TailwindCSS"],
      excerpt: "A LinkedIn Post Scheduler that allows users to preview, ideate, and schedule LinkedIn content. This tool aims to simplify and accelerate content creation and distribution on LinkedIn.",
    },
    {
      isPublished: true,
      isFeatured: true,
      updatedOn: "2024-06-01",
      publishedOn: "2024-06-01",
      slug: "mdx-boilerplate",
      title: "MDX Blog Boilerplate",
      subtitle: "I'm publishing the template code for this MDX blog",
      tags: ["New", "MDX", "NextJS", "TailwindCSS"],
      excerpt: "Extended Markdown (MDX) blogs have two advantages: they're highly customizable and don't require a CMS. There aren't any great templates out there, so I'm making one.",
      externalLink: "https://mdx-blog-amber.vercel.app/"
    },
    {
      isPublished: true,
      isFeatured: false,
      updatedOn: "2024-06-01",
      publishedOn: "2024-06-01",
      slug: "webframe",
      title: "Webframe",
      subtitle: "Outline HTML elements to debug CSS",
      tags: ["HTML", "JS", "CSS", "MV3"],
      excerpt: "I was annoyed debugging CSS layouts so I made 'Webframe', a Chrome extension that outlines HTML elements without affecting the layout to inspect websites and debug CSS.",
      externalLink: "https://chromewebstore.google.com/detail/outline-html-elements/ihlgleabnhekkankfpfoafkobncbfcfo",
      img: "/previews/webframe.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-02",
      slug: "twitter-font-editor",
      title: "Twitter (X) Font Editor",
      subtitle: "Post on X (Twitter) with bold, italic, and underlined fonts",
      tags: ["HTML", "JS", "CSS", "MV3"],
      excerpt: "Google Chrome extension that enables 𝗕𝗼𝗹𝗱, 𝐼𝑡𝑎𝑙𝑖𝑐, and U̲n̲d̲e̲r̲l̲i̲n̲e̲d̲ fonts on X (Twitter) posts by using Unicode characters. A nice way to make use of different font styles without paying for a premium account on X.",
      externalLink: "https://github.com/maxontech/twitter-font-editor",
      img: "/previews/x-font-editor.png",
    },
    {
      isPublished: false,
      isFeatured: true,
      updatedOn: "2024-06-03",
      slug: "click-to-copy",
      title: "Click to Copy",
      subtitle: "Copy text, URLs, and CSS with just a click",
      tags: ["HTML", "CSS", "JQuery", "MV3"],
      excerpt: "A Google Chrome extension that allows you to selectively Copy Text, Urls, and CSS with one Click. Copied items are stored in an integrated clipboard.",
      externalLink: "https://chromewebstore.google.com/detail/click-to-copy/fonpjogfddpklefillfepifbcikebelh",
      img: "/previews/click-to-copy.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-04",
      slug: "gitpro",
      title: "GitPro",
      subtitle: "Showcase website for unique GitHub profiles",
      tags: ["HTML", "TailwindCSS", "JS", "GitHubActions"],
      excerpt: "A showcase website for unique and beautiful GitHub profiles that is fully automated using GitHub Actions. That means profiles submitted via merged pull requests are automatically added to the website.",
      externalLink: "https://maxontech.github.io/best-github-profile-readme/",
      img: "/previews/gitpro.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-05",
      slug: "linkedin-font-editor",
      title: "LinkedIn Font Editor",
      subtitle: "Post on LinkedIn with bold, italic, and underlined fonts",
      tags: ["HTML", "CSS", "JS", "JQuery"],
      excerpt: "Google Chrome extension that enables 𝗕𝗼𝗹𝗱, 𝐼𝑡𝑎𝑙𝑖𝑐, and U̲n̲d̲e̲r̲l̲i̲n̲e̲d̲ Fonts on LinkedIn posts.",
      externalLink: "https://maxontech.io/linkedin-font-editor",
      img: "/previews/linkedin-font-editor.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-06",
      slug: "landinghero",
      title: "LandingHero",
      subtitle: "Showcasing Stunning Landing Pages",
      tags: ["React", "JSX", "Puppeteer"],
      excerpt: "I made my collection of interesting landing pages public on LandingHero, a showcase of beautiful landing pages from various startups, agencies, and businesses.",
      externalLink: "https://landing-page-design-examples.vercel.app/",
      img: "/previews/landinghero.png",
    },
    {
      isPublished: false,
      isFeatured: true,
      updatedOn: "2024-06-07",
      slug: "neft-flappy-bird",
      title: "NEFT Flappy Bird",
      subtitle: "Neuroevolution form Scratch",
      tags: ["Python", "PyGame"],
      excerpt: "Neuroevolution with Fixed Topologies (NEFT) implemented in the Flappy Bird without using any Machine Learning Libraries. This was hard.",
      externalLink: "https://github.com/maxontech/neft-flappy-bird",
      img: "/previews/neft-flappy-bird.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-08",
      slug: "drive-ai",
      title: "Drive AI",
      subtitle: "Exploring AI on 2D Self-Driving Cars",
      tags: ["Python", "PyGame"],
      excerpt: "Neuroevolution with Augmenting Topologies (NEFT) implemented in a 2D Self-Driving Car Simulation.",
      externalLink: "https://github.com/maxontech/DriveAI",
      img: "/previews/drive-ai.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-09",
      slug: "neat-chrome-dinosaur",
      title: "NEAT Chrome Dinosaur",
      subtitle: "My first implementation of NEAT",
      tags: ["Python", "PyGame"],
      excerpt: "Neuroevolution with Augmenting Topologies (NEAT) implemented in Chrome Dinosaur Game. This was the first time I successfully implemented an ML algorithm.",
      externalLink: "https://github.com/maxontech/neat-chrome-dinosaur",
      img: "/previews/neat-chrome-dinosaur.png",
    },
    {
      isPublished: false,
      isFeatured: false,
      updatedOn: "2024-06-10",
      slug: "pathfinding-visualizer",
      title: "Pathfinding Visualizer",
      subtitle: "Visualizing Algorithms in Python",
      tags: ["Python", "PyGame"],
      excerpt: "Simple pathfinding visualizer using the Breadth First Search (BFS) algorithm. I built this using Pygame and Python.",
      externalLink: "https://github.com/maxontech/breadth-first-search",
      img: "/previews/dijkstra-pathfinding.png",
    },

  ];









