import "@/styles/highlight-js/github-dark-dimmed.css";



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MdxLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>


          {children}


    </>
  )
}
