import '@/styles/globals.css';
import "@/styles/highlight-js/github-dark-dimmed.css";
import Image from 'next/image';
import Particles from '@/components/dots/particles';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MdxLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>

      <div className='flex flex-col '>
        <div className='relative -z-10 w-0 h-0  top-[87px] left-[193px]'>
          <Particles numberOfParticles={10} radius={60} opacity={0.2} color='black' left={0} />
          <Particles numberOfParticles={30} radius={300} opacity={0.3} color='black' left={0} />
          <Particles numberOfParticles={40} radius={380} opacity={0.2} color='black' left={0} />
          <Particles numberOfParticles={50} radius={460} opacity={0.1} color='black' left={0} />
          <Particles numberOfParticles={60} radius={540} opacity={0.05} color='black' left={0} />
        </div>
        <div className='flex justify-between  whitespace-nowrap text-slate-600 w-full h-40  text-5xl p-4 mb-6 overflow-hidden mt-8'  >
          <span className="opacity-100 font-bold" /* style={{background: "url('uk-flag.gif')", backgroundSize:"cover", backgroundClip:"text", WebkitTextFillColor:"transparent", backgroundPosition: "center"}} */>Project. </span>
          <span className="opacity-10 hidden sm:block" >Projet. </span>
          <span className="opacity-10 hidden sm:block">プロジェクト. </span>
          <span className="opacity-10 hidden md:block">프로젝트. </span>
          <span className="opacity-10 hidden md:block">项目. </span>
          <span className="opacity-10 hidden lg:block">Проект. </span>
        </div>

        <div className='' >
          {children}
        </div>
      </div>

    </>
  )
}
