
import "@/styles/highlight-js/github-dark-dimmed.css";
import Image from 'next/image';
import Particles from '@/components/dots/particles';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MdxLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>

      <div className='flex flex-col '>


        <div className='' >
          {children}
        </div>
      </div>

    </>
  )
}
